[workspace]
name = "pifenet"
version = "0.1.0"
description = "Pixi environment for PiFeNet with spconv and dependencies"
channels = ["pytorch", "conda-forge", "nvidia", "numba", "open3d-admin"]
platforms = ["linux-64"]

[system-requirements]
cuda = "11.0"

[dependencies]
# cudatoolkit = {version="12.9.1", channel="nvidia"} 
# cudatoolkit-dev = "*"
# cuda-nvcc = {version="*", channel="nvidia"}  
# cudnn = {version="9.12.0", channel="conda-forge"}  
boost = "*"
python = "==3.8.6"
cuda-version = "11.0.*"

[pypi-dependencies]
opencv-python = "*"
setuptools = { version = "*", index = "https://download.pytorch.org/whl/cu110" }
torch = { version = "==1.7.1+cu110", index = "https://download.pytorch.org/whl/cu110" }
torchvision = { version = "==0.8.2+cu110", index = "https://download.pytorch.org/whl/cu110" }
torchaudio = { version = "==0.10.2+cu110", index = "https://download.pytorch.org/whl/cu110" }

[feature.spconv.system-requirements]
cuda = "11.0"

[feature.spconv.dependencies]
# cudatoolkit = {version="12.9.1", channel="nvidia"} 
# cudatoolkit-dev = "*"
# cuda-nvcc = {version="*", channel="nvidia"}
# cudnn = {version="9.12.0", channel="conda-forge"}  
cuda-version = "11.0.*"
# Add these CUDA development packages
# cuda-libraries-dev = {version="13.0", channel="nvidia"}
# cuda-runtime-dev = {version="13.0", channel="nvidia"}
# libcurand-dev = "*"
# libcublas-dev = "*"
# libcusparse-dev = "*"
# libcusolver-dev = "*"
# libcufft-dev = "*"
boost = "*"
python = "==3.8.6"
cmake = "==3.18.2"
setuptools ="*"

[feature.spconv.tasks]
check_cuda = 'python -c "import torch; print(torch.cuda.is_available())"'
setup_cuda_env = '''
export CUDA_HOME=$CONDA_PREFIX
export CUDA_ROOT=$CONDA_PREFIX
export CUDACXX=$CONDA_PREFIX/bin/nvcc
export CPATH=$CONDA_PREFIX/include:$CPATH
'''

[feature.pifenet.dependencies]
addict = "*"
einops = "*"
fire = "*"
jupyterlab = "*"
jupyter-packaging = "*"
tensorboard = "*"
libboost = "*"
matplotlib = "*"
numba = "*"
numpy = "*"
open3d = {version="0.15.1", channel="open3d-admin"}
scikit-image = "*"
psutil = "*"
scikit-learn = "*"
tensorboardx = "*"
pandas = "*"
pillow = "*"
protobuf = "*"
scipy = "*"
seaborn = "*"
tqdm = "*"
yaml = "*"

[feature.pifenet.pypi-dependencies]
spconv = {path = "./spconv/dist", editable=true}

[environments]
spconv=["spconv"]
pifenet=["pifenet"]