[project]
name = "pifenet"
version = "0.1.0"
description = "Pixi environment for PiFeNet with spconv and dependencies"
channels = ["pytorch", "conda-forge", "nvidia", "numba", "open3d-admin"]
platforms = ["linux-64"]

[system-requirements]
cuda = "13"

[dependencies]
cudatoolkit = {version="13.0", channel="nvidia"} 
cudatoolkit-dev = "*"
cuda-nvcc = {version="13.0", channel="nvidia"}  
cudnn = {version="9.12.0", channel="conda-forge"}  
boost = "*"
python = "==3.8.6"

[feature.pifenet.dependencies]
addict = "*"
einops = "*"
fire = "*"
jupyterlab = "*"
jupyter-packaging = "*"
tensorboard = "*"
libboost = "*"
matplotlib = "*"
numba = "*"
numpy = "*"
open3d = {version="0.15.1", channel="open3d-admin"}
scikit-image = "*"
psutil = "*"
scikit-learn = "*"
tensorboardx = "*"
pandas = "*"
pillow = "*"
protobuf = "*"
scipy = "*"
seaborn = "*"
tqdm = "*"
yaml = "*"

[pypi-dependencies]
opencv-python = "*"
torch = { version = "==1.13.1+cu118", index = "https://download.pytorch.org/whl/cu118" }
torchvision = { version = "==0.14.1+cu118", index = "https://download.pytorch.org/whl/cu118" }
torchaudio = { version = "==0.13.1+cu118", index = "https://download.pytorch.org/whl/cu118" }

[feature.spconv.system-requirements]
cuda = "11.8"

[feature.spconv.dependencies]
cudatoolkit = {version="13.0", channel="nvidia"} 
cudatoolkit-dev = "*"
cuda-nvcc = {version="13.0", channel="nvidia"}
# Add these CUDA development packages
cuda-libraries-dev = {version="13.0", channel="nvidia"}
# cuda-runtime-dev = {version="13.0", channel="nvidia"}
libcurand-dev = "*"
libcublas-dev = "*"
libcusparse-dev = "*"
libcusolver-dev = "*"
libcufft-dev = "*"
cudnn = {version="9.12.0", channel="conda-forge"}  
boost = "*"
python = "==3.8.6"
cmake = "==3.18.2"
setuptools ="*"

[feature.spconv.tasks]
check_cuda = 'python -c "import torch; print(torch.cuda.is_available())"'
setup_cuda_env = '''
export CUDA_HOME=$CONDA_PREFIX
export CUDA_ROOT=$CONDA_PREFIX
export CUDACXX=$CONDA_PREFIX/bin/nvcc
export CPATH=$CONDA_PREFIX/include:$CPATH
'''

[feature.pifenet.dependencies]
spconv = {path = "/spconv/dist", editable = true}
[environments]
spconv=["spconv"]
pifenet=["pifenet"]