[workspace]
name = "spconv"
version = "0.1.0"
description = "Pixi environment for building spconv"
channels = ["conda-forge", "pytorch", "nvidia", "numba", "open3d-admin"]
platforms = ["linux-64"]
preview = ["pixi-build"]

# [system-requirements]
# cuda = "11.0.*"

[dependencies]
cudnn = {version="==8.4.1.50", channel="conda-forge"}  
boost = "*"
python = "==3.8.6"
cuda-version = "11.0.*"
git = "*"
gcc = "*"
cudatoolkit = {version="==11.0.221"} 
cudatoolkit-dev = {version="==11.4.0"} 
cuda-nvcc = { version = "==11.7.64", channel = "nvidia"}

make="*"
cmake = "==3.18.2"
gxx_linux-64 = "*"             # GNU C++ compiler
gcc_linux-64 = "*"             # GNU C compiler
ninja = "*"

[pypi-dependencies]
setuptools = { version = "*", index = "https://download.pytorch.org/whl/cu110" }
opencv-python = "*"
torch = { version = "==1.7.1+cu110", index = "https://download.pytorch.org/whl/cu110" }
torchvision = { version = "==0.8.2+cu110", index = "https://download.pytorch.org/whl/cu110" }
# torchaudio = { version = "==0.13.1+cu118", index = "https://download.pytorch.org/whl/cu110" }

[tasks]
check_cuda = 'python -c "import torch; print(torch.cuda.is_available())"'
nvcc_ok = "nvcc --version"
setup_cuda_env = '''
export CUDA_HOME=$CONDA_PREFIX 
export CUDA_PATH=$CONDA_PREFIX 
export CUDAToolkit_ROOT=$CONDA_PREFIX 
export CPATH=$CONDA_PREFIX/include:$CPATH 
export LIBRARY_PATH=$CONDA_PREFIX/lib:$LIBRARY_PATH 
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
'''
start = "python setup.py bdist_wheel"

[package]
name = {workspace = true}
version = {workspace = true}

[package.build.backend]
name = "pixi-build-cmake"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
version = "0.3.*"

[package.build-dependencies]
cudnn = {version="==8.4.1.50", channel="conda-forge"}  
boost = "*"
python = "==3.8.6"
cuda-version = "11.0.*"
git = "*"
gcc = "*"
cudatoolkit = {version="==11.0.221"} 
cudatoolkit-dev = {version="==11.4.0"} 
cuda-nvcc = { version = "==11.7.64", channel = "nvidia"}
make="*"
cmake = "==3.18.2"
gxx_linux-64 = "*"             # GNU C++ compiler
gcc_linux-64 = "*"             # GNU C compiler
ninja = "*"

[package.host-dependencies]
cudnn = {version="==8.4.1.50", channel="conda-forge"}  
boost = "*"
python = "==3.8.6"
cuda-version = "11.0.*"
git = "*"
gcc = "*"
cudatoolkit = {version="==11.0.221"} 
cudatoolkit-dev = {version="==11.4.0"} 
cuda-nvcc = { version = "==11.7.64", channel = "nvidia"}

make="*"
cmake = "==3.18.2"
gxx_linux-64 = "*"             # GNU C++ compiler
gcc_linux-64 = "*"             # GNU C compiler
ninja = "*"