[workspace]
name = "sample_ros2_project"
version = "0.1.0"
description = "Base ROS2 pixi project."
authors = ["Cristobal Medina <krztvl@gmail.com>"]
channels = ["robostack-humble", "conda-forge"]
# Your project can support multiple platforms, the current platform will be automatically added.
platforms = ["linux-64"]

[dependencies]


[feature.dev.dependencies]
pytest = "*"
ruff = "*"
mypy = "*"

[environments]
default = { features = ["dev"], solve-group = "prod" }
prod = { features = [], solve-group = "prod" }

[tasks]
#these are basically shortcuts to be run in a pixi environment. In the future, I should be able to add my custom nodes with tasks, or something.
#Source: https://pixi.sh/latest/tutorials/ros2/#simplify-the-user-experience

#https://github.com/atinfinity/pixi_ros2_gazebo_example
sim = 'ros2 run turtlesim turtlesim_node'
build = 'colcon build --symlink-install'
hello = 'ros2 run my_package my_node'